deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -131,12 +131,12 @@ jobs:
             exit 1
           fi
 
-#          if [ -f Procfile ]; then
+          if [ -f Procfile ]; then
             cp Procfile deploy/Procfile
-#          else
-#            echo "Procfile not found!"
-#            exit 1
-#          fi
+          else
+            echo "Procfile not found!"
+            exit 1
+          fi
           
           if [ -d .ebextensions ]; then
             cp -r .ebextensions deploy/.ebextensions
